2025-09-06 08:51:48 - INFO - ###############################
2025-09-06 08:51:48 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 08:51:48 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 08:51:48 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 08:51:48 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 08:51:48 - INFO - LOGGER STARTED
2025-09-06 08:51:48 - INFO - ###############################
2025-09-06 08:51:48 - INFO - Stated connect to db
2025-09-06 08:51:48 - INFO - Users db created/exist
2025-09-06 08:51:50 - INFO - Start schedule normalization
2025-09-06 08:51:50 - INFO - Schedule is the same. Cancel.
2025-09-06 08:52:07 - INFO - Start schedule normalization
2025-09-06 08:52:07 - INFO - Schedule is the same. Cancel.
2025-09-06 08:52:23 - INFO - Start schedule normalization
2025-09-06 08:52:23 - INFO - Schedule is the same. Cancel.
2025-09-06 08:54:11 - ERROR - Infinity polling: polling exited
2025-09-06 08:54:11 - ERROR - Break infinity polling
2025-09-06 08:55:09 - INFO - ###############################
2025-09-06 08:55:09 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 08:55:09 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 08:55:09 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 08:55:09 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 08:55:09 - INFO - LOGGER STARTED
2025-09-06 08:55:09 - INFO - ###############################
2025-09-06 08:55:09 - INFO - Stated connect to db
2025-09-06 08:55:09 - INFO - Users db created/exist
2025-09-06 08:55:11 - INFO - Start schedule normalization
2025-09-06 08:55:11 - INFO - Schedule is the same. Cancel.
2025-09-06 08:55:27 - INFO - Start schedule normalization
2025-09-06 08:55:27 - INFO - Schedule is the same. Cancel.
2025-09-06 08:56:13 - INFO - Start schedule normalization
2025-09-06 08:56:14 - INFO - Schedule is the same. Cancel.
2025-09-06 10:16:38 - INFO - ###############################
2025-09-06 10:16:38 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 10:16:38 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 10:16:38 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 10:16:38 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 10:16:38 - INFO - LOGGER STARTED
2025-09-06 10:16:38 - INFO - ###############################
2025-09-06 10:16:38 - INFO - Stated connect to db
2025-09-06 10:16:38 - INFO - Users db created/exist
2025-09-06 10:16:39 - INFO - Start schedule normalization
2025-09-06 10:16:39 - INFO - Schedule is the same. Cancel.
2025-09-06 10:24:26 - INFO - ###############################
2025-09-06 10:24:26 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 10:24:26 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 10:24:26 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 10:24:26 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 10:24:26 - INFO - LOGGER STARTED
2025-09-06 10:24:26 - INFO - ###############################
2025-09-06 10:24:26 - INFO - Stated connect to db
2025-09-06 10:24:26 - INFO - Users db created/exist
2025-09-06 10:24:27 - INFO - Start schedule normalization
2025-09-06 10:24:27 - INFO - Schedule is the same. Cancel.
2025-09-06 10:26:09 - INFO - ###############################
2025-09-06 10:26:09 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 10:26:09 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 10:26:09 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 10:26:09 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 10:26:09 - INFO - LOGGER STARTED
2025-09-06 10:26:09 - INFO - ###############################
2025-09-06 10:26:09 - INFO - Stated connect to db
2025-09-06 10:26:09 - INFO - Users db created/exist
2025-09-06 10:26:10 - INFO - Start schedule normalization
2025-09-06 10:26:10 - INFO - Schedule is the same. Cancel.
2025-09-06 10:28:27 - INFO - ###############################
2025-09-06 10:28:27 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 10:28:27 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 10:28:27 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 10:28:27 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 10:28:27 - INFO - LOGGER STARTED
2025-09-06 10:28:27 - INFO - ###############################
2025-09-06 10:28:27 - INFO - Stated connect to db
2025-09-06 10:28:27 - INFO - Users db created/exist
2025-09-06 10:28:29 - INFO - Start schedule normalization
2025-09-06 10:28:29 - INFO - Schedule is the same. Cancel.
2025-09-06 10:31:51 - INFO - ###############################
2025-09-06 10:31:51 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 10:31:51 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 10:31:51 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 10:31:51 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 10:31:51 - INFO - LOGGER STARTED
2025-09-06 10:31:51 - INFO - ###############################
2025-09-06 10:31:51 - INFO - Stated connect to db
2025-09-06 10:31:51 - INFO - Users db created/exist
2025-09-06 10:31:52 - INFO - Start schedule normalization
2025-09-06 10:31:52 - INFO - Schedule is the same. Cancel.
2025-09-06 10:36:54 - INFO - Start schedule normalization
2025-09-06 10:36:54 - INFO - Schedule is the same. Cancel.
2025-09-06 10:41:55 - INFO - Start schedule normalization
2025-09-06 10:41:55 - INFO - Schedule is the same. Cancel.
2025-09-06 10:43:10 - INFO - ###############################
2025-09-06 10:43:10 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 10:43:10 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 10:43:10 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 10:43:10 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 10:43:10 - INFO - LOGGER STARTED
2025-09-06 10:43:10 - INFO - ###############################
2025-09-06 10:43:10 - INFO - Stated connect to db
2025-09-06 10:43:10 - INFO - Users db created/exist
2025-09-06 10:43:11 - INFO - Start schedule normalization
2025-09-06 10:43:11 - INFO - Schedule is the same. Cancel.
2025-09-06 10:43:44 - INFO - ###############################
2025-09-06 10:43:44 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 10:43:44 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 10:43:44 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 10:43:44 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 10:43:44 - INFO - LOGGER STARTED
2025-09-06 10:43:44 - INFO - ###############################
2025-09-06 10:43:44 - INFO - Stated connect to db
2025-09-06 10:43:44 - INFO - Users db created/exist
2025-09-06 10:43:45 - INFO - Start schedule normalization
2025-09-06 10:43:46 - INFO - Schedule is the same. Cancel.
2025-09-06 10:48:47 - INFO - Start schedule normalization
2025-09-06 10:48:47 - INFO - Schedule is the same. Cancel.
2025-09-06 10:52:01 - INFO - ###############################
2025-09-06 10:52:01 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 10:52:01 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 10:52:01 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 10:52:01 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 10:52:01 - INFO - LOGGER STARTED
2025-09-06 10:52:01 - INFO - ###############################
2025-09-06 10:52:01 - INFO - Stated connect to db
2025-09-06 10:52:01 - INFO - Users db created/exist
2025-09-06 10:52:02 - INFO - Start schedule normalization
2025-09-06 10:52:02 - INFO - Schedule is the same. Cancel.
2025-09-06 10:56:51 - INFO - ###############################
2025-09-06 10:56:51 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 10:56:51 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 10:56:51 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 10:56:51 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 10:56:51 - INFO - LOGGER STARTED
2025-09-06 10:56:51 - INFO - ###############################
2025-09-06 10:56:51 - INFO - Stated connect to db
2025-09-06 10:56:51 - INFO - Users db created/exist
2025-09-06 10:56:52 - INFO - Start schedule normalization
2025-09-06 10:56:52 - INFO - Schedule is the same. Cancel.
2025-09-06 10:58:41 - INFO - ###############################
2025-09-06 10:58:41 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 10:58:41 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 10:58:41 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 10:58:41 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 10:58:41 - INFO - LOGGER STARTED
2025-09-06 10:58:41 - INFO - ###############################
2025-09-06 10:58:41 - INFO - Stated connect to db
2025-09-06 10:58:41 - INFO - Users db created/exist
2025-09-06 10:58:42 - INFO - Start schedule normalization
2025-09-06 10:58:42 - INFO - Schedule is the same. Cancel.
2025-09-06 10:58:51 - ERROR - Infinity polling exception: 'list' object has no attribute 'to_dict'
2025-09-06 10:58:51 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 9759, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\telegram_bot\main.py", line 121, in choice_parallel
    markup_parallel.add(buttons)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\types.py", line 2549, in add
    button_array.append(button.to_dict())
                        ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'to_dict'

2025-09-06 10:59:35 - INFO - ###############################
2025-09-06 10:59:35 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 10:59:35 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 10:59:35 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 10:59:35 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 10:59:35 - INFO - LOGGER STARTED
2025-09-06 10:59:35 - INFO - ###############################
2025-09-06 10:59:35 - INFO - Stated connect to db
2025-09-06 10:59:35 - INFO - Users db created/exist
2025-09-06 10:59:36 - INFO - Start schedule normalization
2025-09-06 10:59:37 - INFO - Schedule is the same. Cancel.
2025-09-06 10:59:37 - ERROR - Infinity polling exception: 'list' object has no attribute 'to_dict'
2025-09-06 10:59:37 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 9759, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\telegram_bot\main.py", line 121, in choice_parallel
    markup_parallel.add(buttons)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\types.py", line 2549, in add
    button_array.append(button.to_dict())
                        ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'to_dict'

2025-09-06 11:00:18 - INFO - ###############################
2025-09-06 11:00:18 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 11:00:18 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 11:00:18 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 11:00:18 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 11:00:18 - INFO - LOGGER STARTED
2025-09-06 11:00:18 - INFO - ###############################
2025-09-06 11:00:18 - INFO - Stated connect to db
2025-09-06 11:00:18 - INFO - Users db created/exist
2025-09-06 11:00:19 - INFO - Start schedule normalization
2025-09-06 11:00:19 - INFO - Schedule is the same. Cancel.
2025-09-06 11:00:23 - ERROR - Infinity polling exception: 'list' object has no attribute 'to_dict'
2025-09-06 11:00:23 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 9759, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\telegram_bot\main.py", line 121, in choice_parallel
    markup_parallel.add(buttons)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\types.py", line 2549, in add
    button_array.append(button.to_dict())
                        ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'to_dict'

2025-09-06 11:01:25 - INFO - ###############################
2025-09-06 11:01:25 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 11:01:25 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 11:01:25 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 11:01:25 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 11:01:25 - INFO - LOGGER STARTED
2025-09-06 11:01:25 - INFO - ###############################
2025-09-06 11:01:25 - INFO - Stated connect to db
2025-09-06 11:01:25 - INFO - Users db created/exist
2025-09-06 11:01:26 - INFO - Start schedule normalization
2025-09-06 11:01:26 - INFO - Schedule is the same. Cancel.
2025-09-06 11:05:32 - INFO - ###############################
2025-09-06 11:05:32 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 11:05:32 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 11:05:32 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 11:05:32 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 11:05:32 - INFO - LOGGER STARTED
2025-09-06 11:05:32 - INFO - ###############################
2025-09-06 11:05:32 - INFO - Stated connect to db
2025-09-06 11:05:32 - INFO - Users db created/exist
2025-09-06 11:05:33 - INFO - Start schedule normalization
2025-09-06 11:05:34 - INFO - Schedule normalized
2025-09-06 11:05:44 - ERROR - Infinity polling exception: 'list' object has no attribute 'keys'
2025-09-06 11:05:44 - ERROR - Exception traceback:
Traceback (most recent call last):
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "K:\Scedule_Bot_1.0\.venv\Lib\site-packages\telebot\__init__.py", line 9759, in _run_middlewares_and_handler
    result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\Scedule_Bot_1.0\telegram_bot\main.py", line 115, in choice_parallel
    for parallel in list(get_classes().keys()):
                         ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'keys'

2025-09-06 11:06:16 - INFO - ###############################
2025-09-06 11:06:16 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 11:06:16 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 11:06:16 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 11:06:16 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 11:06:16 - INFO - LOGGER STARTED
2025-09-06 11:06:16 - INFO - ###############################
2025-09-06 11:06:16 - INFO - Stated connect to db
2025-09-06 11:06:16 - INFO - Users db created/exist
2025-09-06 11:06:17 - INFO - Start schedule normalization
2025-09-06 11:06:17 - INFO - Schedule is the same. Cancel.
2025-09-06 11:08:02 - INFO - ###############################
2025-09-06 11:08:02 - INFO - TEST INFO LOGGING FINALLY
2025-09-06 11:08:02 - WARNING - TEST WARNING LOGGING FINALLY
2025-09-06 11:08:02 - ERROR - Error to: utils.my_logger | Index: 0
NoneType: None
2025-09-06 11:08:02 - CRITICAL - TEST FATAL LOGGING FINALLY
2025-09-06 11:08:02 - INFO - LOGGER STARTED
2025-09-06 11:08:02 - INFO - ###############################
2025-09-06 11:08:02 - INFO - Stated connect to db
2025-09-06 11:08:02 - INFO - Users db created/exist
2025-09-06 11:08:03 - INFO - Start schedule normalization
2025-09-06 11:08:03 - INFO - Schedule normalized
